name: crawl
on:
  push:
    branches:
      - main
  schedule:
    - cron:  '0 0 */1 * *'
    
jobs:
  Crawl:
    strategy:
      matrix:
        school_year: [89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109]
        semester: [1,2,3]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.5.1
    - name: Install npm packages
      run: npm install
    - name: Run script
      run: node test.js ${{ matrix.school_year }}-${{ matrix.semester }}
    - name: Git
      run: |
        git config --local user.email "nelson22768384@gmail.com" 
        git config --local user.name "5idereal"
        git add .
        git commit -m "crawl"
        git push
    
